# Build the manager binary
FROM golang:1.24-alpine AS builder
RUN apk add make binutils git
COPY / /work
WORKDIR /work

RUN make controller

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /work/bin/controller /controller
USER 65532:65532

ENTRYPOINT ["/controller"]
