ARG GOOS
ARG GOARCH
FROM alpine:3.20
ARG GOOS
ARG GOARCH
LABEL maintainers="Metal Authors"
LABEL description="LVM Driver"

RUN apk add lvm2 lvm2-extra e2fsprogs e2fsprogs-extra smartmontools nvme-cli util-linux device-mapper xfsprogs xfsprogs-extra
COPY bin/lvmplugin-${GOOS}-${GOARCH} /lvmplugin
USER root
ENTRYPOINT ["/lvmplugin"]
