//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *DRBDVolume) DeepCopyInto(out *DRBDVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DRBDVolume) DeepCopy() *DRBDVolume {
	if in == nil {
		return nil
	}
	out := new(DRBDVolume)
	in.DeepCopyInto(out)
	return out
}

func (in *DRBDVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DRBDVolumeList) DeepCopyInto(out *DRBDVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DRBDVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DRBDVolumeList) DeepCopy() *DRBDVolumeList {
	if in == nil {
		return nil
	}
	out := new(DRBDVolumeList)
	in.DeepCopyInto(out)
	return out
}

func (in *DRBDVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DRBDVolumeSpec) DeepCopyInto(out *DRBDVolumeSpec) {
	*out = *in
}

func (in *DRBDVolumeSpec) DeepCopy() *DRBDVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(DRBDVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DRBDVolumeStatus) DeepCopyInto(out *DRBDVolumeStatus) {
	*out = *in
	if in.DegradedSince != nil {
		in, out := &in.DegradedSince, &out.DegradedSince
		*out = (*in).DeepCopy()
	}
}

func (in *DRBDVolumeStatus) DeepCopy() *DRBDVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(DRBDVolumeStatus)
	in.DeepCopyInto(out)
	return out
}
