apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-sc-linear
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
