apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-mirror
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-driver-lvm-mirror
