---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    metal-stack.io/csi-driver-lvm.is-eviction-allowed: "true"
  name: test-pvc
spec:
  storageClassName: "csi-driver-lvm-linear" 
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: one-replica-nginx
  labels:
    app: nginx
spec:
  serviceName: "nginx" 
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: test-pv
        persistentVolumeClaim:
          claimName: test-pvc
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
        - mountPath: "/test-data"
          name: test-pv
  volumeClaimTemplates:
  - metadata:
      name: my-csi-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-driver-lvm-linear