{{- if .Values.rbac.create }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-lvmplugin
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-lvmplugin-runner
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-lvmplugin-role
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: csi-lvmplugin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: external-lvmplugin-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-lvmplugin-cfg
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-lvmplugin-role-cfg
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: csi-lvmplugin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: external-lvmplugin-cfg
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-lvmplugin
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-lvmplugin-role
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: csi-lvmplugin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: csi-lvmplugin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
