name: "CI job using minikube"
on: [pull_request]

jobs:
  cijob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v1.0.0
      with:
        minikube version: 'v1.5.1'
        kubernetes version: 'v1.17.2'
    - name: Testing
      run: |
        minikube update-context
        kubectl cluster-info
        make cijob
